services:
  vonage-verify:
    image: vonage-verify:latest
    build:
      context: .
      args:
        - PORT=${PORT}
    container_name: vonage-verify
    ports:
      - '127.0.0.1:${PORT}:${PORT}'
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - ./logs:/app/logs
    networks:
      - local_net

  mongo:
    image: mongo:7.0
    container_name: verifier-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    networks:
      - local_net

volumes:
  mongo-data:

networks:
  local_net:
    driver: bridge
