// Official Vonage SDK for SMS sending and verification
import { Auth } from '@vonage/auth';
import { Verify } from '@vonage/verify';
import logger from '../utils/logger.js';

const credentials = new Auth({
  apiKey: process.env.VONAGE_API_KEY,
  apiSecret: process.env.VONAGE_API_SECRET
});
const options = {};
const verifyClient = new Verify(credentials, options);

function getVerifyBrand() {
  return process.env.VONAGE_VERIFY_BRAND?.trim() || 'Traixo';
}

function isFormattedError(err) {
  return err instanceof Error && /^\[[A-Z0-9]+\]/.test(err.message);
}

/**
 * Start the verification process via SMS using the Vonage Verify API.
 *
 * @param {string} phoneNumber - Phone number in international format (e.g. +521234567890)
 * @throws {Error} - If the API returns an error or status other than '0'
 *
 * @returns {Promise<string>} - Verification request ID (`request_id`) generated by Vonage
 */
export async function startVerification(phoneNumber) {
    logger.info(`[Vonage] Sending verification to: ${phoneNumber}`);

    try {
        const result = await verifyClient.start({
            number: phoneNumber,
            brand: getVerifyBrand(),
            workflow_id: 2,
        });

        logger.info(`[Vonage Verify] Result: ${JSON.stringify(result)}`);

        if (result.status !== '0') {
            logger.error(`[Vonage Verify] Error de API: ${result.error_text}`);
            throw new Error(`[V001] ${result.error_text || 'Verification could not be started'}`);
        }

        return result.request_id;
    } catch (err) {
        if (isFormattedError(err)) throw err;
        logger.error(`[Vonage Verify] Error de red o SDK: ${err}`);
        throw new Error('[E500] Verification failed. Please try again later.');
    }
}

/**
 * Verifies the code entered by the user, using the Vonage request_id.
 *
 * @param {string} requestId - ID generated by Vonage when starting verification
 * @param {string} code - Verification code entered by the user
 * @throws {Error} - If verification fails or the code is invalid
 *
 * @returns {Promise<boolean>} - true if the code is correct
 */
export async function checkVerification(requestId, code) {
    try {
        const result = await verifyClient.check({
            request_id: String(requestId),
            code: String(code),
        });

        logger.info(`[Vonage Verify] Verification: ${JSON.stringify(result)}`);

        if (result.status !== '0') {
            throw new Error(`[V002] ${result.error_text || 'Incorrect or expired code'}`);
        }

        return true;
    } catch (err) {
        if (isFormattedError(err)) throw err;
        logger.error(`[Vonage Verify] Error en verificación: ${err}`);
        throw new Error('[E500] The code could not be verified. Please try again.');
    }
}
