// Official Vonage SDK for SMS sending and verification
import { Auth } from '@vonage/auth';
import { Verify } from '@vonage/verify';
import logger from '../utils/logger.js';

const credentials = new Auth({
  apiKey: process.env.VONAGE_API_KEY,
  apiSecret: process.env.VONAGE_API_SECRET
});
const options = {};
const verifyClient = new Verify(credentials, options);

function getVerifyBrand() {
  return process.env.VONAGE_VERIFY_BRAND?.trim() || 'Traixo';
}

function isFormattedError(err) {
  return err instanceof Error && /^\[[A-Z0-9]+\]/.test(err.message);
}

function readStatus(result) {
  return result?.status != null ? String(result.status) : '';
}

function readErrorText(result) {
  return result?.errorText || result?.error_text || 'Unknown error';
}

function readRequestId(result) {
  return result?.requestId || result?.request_id || null;
}

/**
 * Start the verification process via SMS using the Vonage Verify API.
 *
 * workflow_id 1 = solo SMS (sin reenvío automático ni llamada TTS).
 *
 * @param {string} phoneNumber - Phone number in international format (e.g. +521234567890)
 * @throws {Error} - If the API returns an error or status other than '0'
 *
 * @returns {Promise<string>} - Verification request ID generated by Vonage
 */
export async function startVerification(phoneNumber) {
    logger.info(`[Vonage] Sending verification to: ${phoneNumber}`);

    try {
        const result = await verifyClient.start({
            number: phoneNumber,
            brand: getVerifyBrand(),
            // 1 = SMS only. Otros workflows reenvían SMS o llaman a los ~2-3 min.
            workflow_id: 1,
            code_length: 4,
        });

        logger.info(`[Vonage Verify] Result: ${JSON.stringify(result)}`);

        if (readStatus(result) !== '0') {
            logger.error(`[Vonage Verify] Error de API: ${readErrorText(result)}`);
            throw new Error(`[V001] ${readErrorText(result) || 'Verification could not be started'}`);
        }

        const requestId = readRequestId(result);
        if (!requestId) {
            throw new Error('[V001] Vonage did not return a request_id');
        }

        return String(requestId);
    } catch (err) {
        if (isFormattedError(err)) throw err;
        logger.error(`[Vonage Verify] Error de red o SDK: ${err}`);
        throw new Error('[E500] Verification failed. Please try again later.');
    }
}

/**
 * Verifies the code entered by the user, using the Vonage request_id.
 *
 * @param {string} requestId - ID generated by Vonage when starting verification
 * @param {string} code - Verification code entered by the user
 * @throws {Error} - If verification fails or the code is invalid
 *
 * @returns {Promise<boolean>} - true if the code is correct
 */
export async function checkVerification(requestId, code) {
    const safeRequestId = String(requestId ?? '').trim();
    const safeCode = String(code ?? '').trim();

    if (!safeRequestId || !safeCode) {
        throw new Error('[V002] requestId and code are required');
    }

    try {
        // El SDK espera dos argumentos posicionales, NO un objeto.
        // check({ request_id, code }) enviaba "[object Object]" como request_id.
        const result = await verifyClient.check(safeRequestId, safeCode);

        logger.info(`[Vonage Verify] Verification: ${JSON.stringify(result)}`);

        if (readStatus(result) !== '0') {
            throw new Error(`[V002] ${readErrorText(result) || 'Incorrect or expired code'}`);
        }

        return true;
    } catch (err) {
        if (isFormattedError(err)) throw err;
        logger.error(`[Vonage Verify] Error en verificación: ${err}`);
        throw new Error('[E500] The code could not be verified. Please try again.');
    }
}
