// Official Vonage SDK for SMS sending and verification
import { Auth } from '@vonage/auth';
import { Verify } from '@vonage/verify';

const credentials = new Auth({
  apiKey: process.env.VONAGE_API_KEY,
  apiSecret: process.env.VONAGE_API_SECRET
});
const options = {};
// Vonage verifyClient instance
const verifyClient  = new Verify(credentials, options);

/**
 * Start the verification process via SMS using the Vonage Verify API.
 * 
 * @param {string} phoneNumber - Phone number in international format (e.g. +521234567890)
 * @throws {Error} - If the API returns an error or status other than '0'
 * 
 * @returns {Promise<string>} - Verification request ID (`request_id`) generated by Vonage
 * 
 * @link https://www.npmjs.com/package/%40vonage/server-sdk
 */
export async function startVerification(phoneNumber) {
    console.log('[Vonage] Sending verification to:', phoneNumber);

    try {

        const result = await verifyClient.start({
            number: phoneNumber,
            brand: 'MyApp',
            workflow_id: 2,
        });

        console.log('[Vonage Verify] Resultado:', result);

        if (result.status !== '0') {
            console.log('[Vonage Verify] Error de API:', result.error_text);
            throw new Error(`Vonage error (${result.status}): ${result.error_text || 'Error al iniciar la verificación'}`);
        }

        return result.request_id;

    } catch (err) {
        console.error('[Vonage Verify] Error de red o SDK:', err);
        throw new Error('No se pudo iniciar la verificación. Intenta más tarde.');
    }

}

/**
 * Verifies the code entered by the user, using the Vonage request_id.
 * 
 * @param {string} requestId - ID generated by Vonage when starting verification
 * @param {string} code - Verification code entered by the user
 * @throws {Error} - If verification fails or the code is invalid
 * 
 * @returns {Promise<boolean>} - true if the code is correct
 * 
 * @link https://www.npmjs.com/package/%40vonage/server-sdk
 */
export async function checkVerification(requestId, code) {
    try {
        const result = await verifyClient.check({
            request_id: requestId,
            code,
        });

        console.log('[Vonage Verify] Verification:', result);

        if (result.status !== '0') {
            throw new Error(result.error_text || 'Incorrect or expired code');
        }

        return true;
    } catch (err) {
        console.error('[Vonage Verify] Error en verificación:', err)
        throw new Error('No se pudo verificar el código. Intenta nuevamente.')
    }

}
