// Official Vonage SDK for SMS sending and verification
import { Vonage } from '@vonage/server-sdk';


const credentials = {
  apiKey: process.env.VONAGE_API_KEY,
  apiSecret: process.env.VONAGE_API_SECRET,
}
const options = {}
// Vonage instance
const vonage = new Vonage(credentials, options)

/**
 * Start the verification process via SMS using the Vonage Verify API.
 * 
 * @param {string} phoneNumber - Phone number in international format (e.g. +521234567890)
 * @returns {Promise<string>} - Verification request ID (`request_id`) generated by Vonage
 * @throws {Error} - If the API returns an error or status other than '0'
 * 
 * @link https://www.npmjs.com/package/%40vonage/server-sdk
 */
export function startVerification(phoneNumber) {
    console.log('[Vonage] Sending verification to:', phoneNumber);
    return new Promise((resolve, reject) => {
        vonage.verify.start(
            {
                number: phoneNumber,
                brand: 'MiApp',
                workflow_id: 2
            },
            (err, result) => {
                console.log('[Vonage Callback] err:', err)
                console.log('[Vonage Callback] result:', result)
                if (err) return reject(err)
                if (result.status !== '0') return reject(new Error(result.error_text))
                resolve(result.request_id)  
            }
        )
    })
}

/**
 * Verifies the code entered by the user, using the Vonage request_id.
 * 
 * @param {string} requestId - ID generated by Vonage when starting verification
 * @param {string} code - Verification code entered by the user
 * @returns {Promise<boolean>} - true if the code is correct
 * @throws {Error} - If verification fails or the code is invalid
 * 
 * @link https://www.npmjs.com/package/%40vonage/server-sdk
 */
export function checkVerification(requestId, code) {
    return new Promise((resolve, reject) => {
        vonage.verify.check({ request_id: requestId, code }, (err, result) => {
            if (err) return reject(err)
            if (result.status !== '0') return reject(new Error(result.error_text))
            resolve(true)
        })
    })
}
