// Imports Vonage service functions to initiate and verify codes
import {
    startVerification as start,
    checkVerification as check
} from '../services/vonageService.js';
// Utility to clean and validate phone numbers
import sanitizePhone from '../utils/phoneSanitizer.js';

/**
 * Controller to initiate SMS verification.
 * 
 * 1. Receives a phone number in the request body.
 * 2. Sanitizes and validates the number (only Mexican numbers with +52 are allowed).
 * 3. Calls Vonage to initiate the verification flow.
 * 4. Returns the requestId generated by Vonage (used later to validate the code).
 * 
 * @param {import('express').Request} req - HTTP request that must include `phone` in the body
 * @param {import('express').Response} res - HTTP Response Object
 * 
 * @returns {void}
 */
export async function startVerification(req, res) {
    try {
        // Sanitize and validate the phone number
        const phone = sanitizePhone(req.body.phone);

        // Call Vonage service to start verification
        const requestId = await start(phone);

        // Responds with the ID that will be used to validate the code
        res.json({ requestId });
    } catch (err) {
        // In case of error (malformed number, Vonage error, etc.)
        res.status(400).json({ message: err.message || 'Error starting verification' });
    }
}

/**
 * Controller to verify a verification code sent via SMS.
 * 
 * 1. Receives a `requestId` and a `code` in the request body.
 * 2. Validates that both fields exist.
 * 3. Calls Vonage to verify the code.
 * 4. If correct, responds successfully.
 * 
 * @param {import('express').Request} req - HTTP request that must include `requestId` and `code` in the body
 * @param {import('express').Response} res - HTTP Response Object
 * 
 * @returns {void}
 */
export async function checkVerification(req, res) {
    try {

        const { requestId, code } = req.body;

        // Basic validation of required fields
        if (!requestId || !code) {
            return res.status(400).json({
                status: 'missing_fields',
                message: 'Se requiere requestId y code',
            })
        }

        // Call Vonage service to validate the code
        await check(requestId, code);

        // Response in case of successful verification
        res.json({ success: true });
    } catch (err) {
        // Verification failed (incorrect code, expired, etc.)
        res.status(400).json({ message: err.message || 'Error al verificar el código' });
    }
}
