// Imports Vonage service functions to initiate and verify codes
import {
    startVerification as start,
    checkVerification as check
} from '../services/vonageService.js';
import { sanitizePhone } from '../utils/phoneSanitizer.js';
import { sendResponse } from '../utils/sendResponse.js'

/**
 * Controller to initiate SMS verification.
 * 
 * 1. Receives a phone number in the request body.
 * 2. Sanitizes and validates the number (only Mexican numbers with +52 are allowed).
 * 3. Calls Vonage to initiate the verification flow.
 * 4. Returns the requestId generated by Vonage (used later to validate the code).
 * 
 * @param {import('express').Request} req - HTTP request that must include `phone` in the body
 * @param {import('express').Response} res - HTTP Response Object
 * 
 * @returns {void}
 */
export async function startVerification(req, res) {
    try {
        // Sanitize and validate the phone number
        const phone = sanitizePhone(req.body.phone);

        console.log('[startVerification] phone:', phone);

        if (!phone) {
            return sendResponse(
                res,
                400,
                'invalid_phone',
                'Invalid or missing phone number'
            );
        }

        // Call Vonage service to start verification
        const requestId = await start(phone);

        console.log('[startVerification] requestId:', requestId);

        // Responds with the ID that will be used to validate the code
        return sendResponse(
            res,
            200,
            'verification_started',
            'Verification started',
            { requestId }
        );
    } catch (err) {
        console.error('[startVerification] Error:', err);
        // In case of error (malformed number, Vonage error, etc.)

        const isExpectedError = err.message?.includes('Vonage') || err.message?.includes('verificación');
        return sendResponse(
            isExpectedError ? 400 : 500,
            'verification_start_failed',
            err.message || 'Internal server error'
        );
    }
}

/**
 * Controller to verify a verification code sent via SMS.
 * 
 * 1. Receives a `requestId` and a `code` in the request body.
 * 2. Validates that both fields exist.
 * 3. Calls Vonage to verify the code.
 * 4. If correct, responds successfully.
 * 
 * @param {import('express').Request} req - HTTP request that must include `requestId` and `code` in the body
 * @param {import('express').Response} res - HTTP Response Object
 * 
 * @returns {void}
 */
export async function checkVerification(req, res) {
    try {

        const { requestId, code } = req.body;

        // Basic validation of required fields
        if (!requestId || !code) {
            return sendResponse(
                res,
                400,
                'missing_fields',
                'requestId and code are required'
            );
        }

        // Call Vonage service to validate the code
        await check(requestId, code);

        // Response in case of successful verification
        return sendResponse(
            res,
            200,
            'verification_successful',
            'Code verified successfully'
        );
    } catch (err) {
        console.error('[checkVerification] Error:', err);
        // Verification failed (incorrect code, expired, etc.)
        const isExpectedError = err.message?.includes('código') || err.message?.includes('verificar');
        return sendResponse(
            isExpectedError ? 400 : 500,
            'verification_failed',
            err.message || 'Internal server error'
        );
    }
}
